#!/usr/bin/env bash

set -e

# For the check step concourse will set the following environment variables:
# SOURCE_PATH - path to component repository root directory.

if [[ -z "${SOURCE_PATH}" ]]; then
  SOURCE_PATH="$(readlink -f "$(dirname "${0}")/..")"
  export SOURCE_PATH
else
  SOURCE_PATH="$(readlink -f "${SOURCE_PATH}")"
  export SOURCE_PATH
fi

# Install Golint.
if ! which golangci-lint 1>/dev/null; then
  echo -n "Installing golangci-lint... "
  curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "$(go env GOPATH)"/bin v1.64.7
fi

golangci-lint --version

cd "$SOURCE_PATH"
# Execute static code checks.
go vet ./...
# Execute lint check
golangci-lint run

if [ -n "$(gofmt -l .)" ]; then
  echo "Formatting errors:"
  gofmt -l .
  exit 1
fi

# Execute unittests
go test ./...

cd - >/dev/null
