{
 "title": "Shoot Customization",
 "description": "Dashboard with Information to the amount of custom configured Shoot clusters.",
 "tags": [
  "Shoot",
  "Gardener"
 ],
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hibernated Shoots",
   "type": "singlestat",
   "description": "Amount of hibernated Shoots.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "garden_shoots_hibernation_enabled_total"
    }
   ]
  },
  {
   "title": "Shoots with Hibernation Schedule",
   "type": "singlestat",
   "description": "Amount of Shoots which have an hibernation schedule configured.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "garden_shoots_hibernation_schedule_total"
    }
   ]
  },
  {
   "title": "Shoots with Privileged Container",
   "type": "singlestat",
   "description": "Count of Shoots which allow privileged containers.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "garden_shoots_custom_privileged_containers_total"
    }
   ]
  },
  {
   "title": "Shoots with Custom DNS Domain",
   "type": "singlestat",
   "description": "Count of Shoots which use a custom dns domain.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "garden_shoots_custom_network_customdomain_total"
    }
   ]
  },
  {
   "title": "Shoots with Maintenance Window",
   "type": "singlestat",
   "description": "Count of Shoots which have a maintenance window configured.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "garden_shoots_maintenance_window_total"
    }
   ]
  },
  {
   "title": "Shoots with K8S Patch Version Autoupdate",
   "type": "singlestat",
   "description": "Count of Shoots which have autoupdate for kubernetes versions configured.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "garden_shoots_maintenance_autoupdate_k8sversion_total"
    }
   ]
  },
  {
   "title": "Shoots with Machine Image Version Autoupdate",
   "type": "singlestat",
   "description": "Count of Shoots which have autoupdate for machine image versions configured.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "garden_shoots_maintenance_autoupdate_imageversion_total"
    }
   ]
  },
  {
   "title": "Shoot with Extensions",
   "type": "graph",
   "description": "Count of Shoots which have an extension(s) configured.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "garden_shoots_custom_extensions_total",
     "legendFormat": "{{extension}}"
    }
   ]
  },
  {
   "title": "Shoots Proxy Mode Configurations",
   "type": "graph",
   "description": "Count of Shoots which by proxy mode configuration for the kube proxy.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "garden_shoots_custom_proxy_mode_total",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  { "title": "kube-apiserver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Shoot apiservers with Basic Auth",
   "type": "singlestat",
   "description": "Count of Shoots which have basic auth enabled on the kube apiserver.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "garden_shoots_custom_apiserver_basicauth_total"
    }
   ]
  },
  {
   "title": "Shoot apiservers with Audit Log Policy",
   "type": "singlestat",
   "description": "Count of Shoots which have an audit log policy configured for the kube apiserver.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "garden_shoots_custom_apiserver_auditpolicy_total"
    }
   ]
  },
  {
   "title": "Shoot apiservers with OIDC Configuration",
   "type": "singlestat",
   "description": "Count of Shoots which have an open id connect coniguration for the kube apiserver.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "garden_shoots_custom_apiserver_oidcconfig_total"
    }
   ]
  },
  {
   "title": "Shoot apiservers with Feature Gates",
   "type": "graph",
   "description": "Count of Shoots with enabled kube apiserver feature gates.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "garden_shoots_custom_apiserver_featuregates_total",
     "legendFormat": "{{featuregate}}"
    }
   ]
  },
  {
   "title": "Shoot apiservers with Admission Plugins",
   "type": "graph",
   "description": "Count of Shoots with enabled kube apiserver admission plugins.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "garden_shoots_custom_apiserver_admissionplugins_total",
     "legendFormat": "{{admissionplugin}}"
    }
   ]
  },
  { "title": "Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Shoots with multiple Worker Pools",
   "type": "singlestat",
   "description": "Count of Shoots with multiple worker pools.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "garden_shoots_custom_worker_multiplepools_total"
    }
   ]
  },
  {
   "title": "Shoots with multi zone Worker Pools",
   "type": "singlestat",
   "description": "Count of Shoots with multi zone worker pools.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "garden_shoots_custom_worker_multizones_total"
    }
   ]
  },
  {
   "title": "Shoot with Worker Pools Taints",
   "type": "singlestat",
   "description": "Count of Shoots with worker pool taints.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "garden_shoots_custom_worker_taints_total"
    }
   ]
  },
  {
   "title": "Shoot with Worker Pools Labels",
   "type": "singlestat",
   "description": "Count of Shoots with worker pool labels.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "garden_shoots_custom_worker_labels_total"
    }
   ]
  },
  {
   "title": "Shoot with Worker Pool Annotations",
   "type": "singlestat",
   "description": "Count of Shoots with worker pool annotations.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "garden_shoots_custom_worker_annotations_total"
    }
   ]
  },
  { "title": "kube-controller-manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Shoots with Node CIDR Mask Size Configuration",
   "type": "singlestat",
   "description": "Count of Shoots which have node cidr mask size configured on the kube controller manager.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "garden_shoots_custom_kcm_nodecidrmasksize_total"
    }
   ]
  },
  {
   "title": "Shoot Kube Controller Manager with Horizontal Autoscaling",
   "type": "singlestat",
   "description": "Count of Shoots with horizontal pod autoscaling for the kube controller manager.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "garden_shoots_custom_kcm_horizontalpodautoscale_total"
    }
   ]
  },
  {
   "title": "Shoot Kube Controller Manager with Feature Gates",
   "type": "graph",
   "description": "Count of Shoots with enabled kube controller manager feature gates.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "garden_shoots_custom_kcm_featuregates_total",
     "legendFormat": "{{featuregate}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Shoots with Kubelet Pod PID Limit Configuration",
   "type": "singlestat",
   "description": "Count of Shoots which have a pod pid limit configured for the kubelet(s).",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "garden_shoots_custom_kubelet_podpidlimit_total"
    }
   ]
  },
  {
   "title": "Shoot Kube Schedulers with Feature Gates",
   "type": "graph",
   "description": "Count of Shoots with enabled kube scheduler feature gates.",
   "gridPos": { "h": 4, "w": 12, "x": 6, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "garden_shoots_custom_scheduler_featuregates_total",
     "legendFormat": "{{admissionplugin}}"
    }
   ]
  },
  {
   "title": "Shoots with Nginx Ingress Addon",
   "type": "singlestat",
   "description": "Count of Shoots which have nginx ingress conroller addon enabled.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 41 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "garden_shoots_custom_addon_nginxingress_total"
    }
   ]
  },
  {
   "title": "Shoots with Kube-Dashboard Addon",
   "type": "singlestat",
   "description": "Count of Shoots which have kubernetes dashboard addon enabled.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 41 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "garden_shoots_custom_addon_kubedashboard_total"
    }
   ]
  }
 ]
}