{
 "title": "Shoot Details",
 "description": "Dashboard with details to a Shoot clusters state.",
 "tags": [
  "Shoot",
  "Gardener"
 ],
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(garden_shoot_info, project)"
   },
   {
    "name": "shoot",
    "label": "Shoot",
    "query": "label_values(garden_shoot_info{project=\"$project\"}, name)"
   }
  ]
 },
 "panels": [
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Infrastructure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "garden_shoot_info{project=\"$project\", name=\"$shoot\"}",
     "legendFormat": "{{iaas}}"
    }
   ]
  },
  {
   "title": "Region",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "garden_shoot_info{project=\"$project\", name=\"$shoot\"}",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Seed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "garden_shoot_info{project=\"$project\", name=\"$shoot\"}",
     "legendFormat": "{{seed}}"
    }
   ]
  },
  {
   "title": "K8S Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "garden_shoot_info{project=\"$project\", name=\"$shoot\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "garden_shoot_node_max_total{project=\"$project\", name=\"$shoot\"}"
    }
   ]
  },
  {
   "title": "State of Last Operation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Shoot State" }
   ],
   "targets": [
    {
     "expr": "garden_shoot_operation_states{project=\"$project\", name=\"$shoot\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 4 },
   "content": "##### State legend\n0 = operation not active  \n1 = succeeded  \n2 = processing  \n3 = pending  \n4 = error  \n5 = failed  \n"
  },
  { "title": "State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Conditions (0=false, 1=ok, -1=unknown)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Condition State" }
   ],
   "targets": [
    {
     "expr": "garden_shoot_condition{condition=\"SystemComponentsHealthy\",project=\"$project\", name=\"$shoot\"}",
     "legendFormat": "{{condition}}"
    },
    {
     "expr": "garden_shoot_condition{condition=\"EveryNodeReady\",project=\"$project\", name=\"$shoot\"}",
     "legendFormat": "{{condition}}"
    },
    {
     "expr": "garden_shoot_condition{condition=\"ControlPlaneHealthy\",project=\"$project\", name=\"$shoot\"}",
     "legendFormat": "{{condition}}"
    }
   ]
  }
 ]
}