{
 "title": "Shoot States Overview",
 "description": "Dashboard with information to the Shoot cluster states.",
 "tags": [
  "Gardener",
  "Shoot"
 ],
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "iaas",
    "label": "Infrastructure",
    "query": "label_values(garden_shoot_operations_total, iaas)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Shoots in Healthy State",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(garden_shoot_operations_total{iaas=~\"$iaas\", state!~\"Error|Failed\"})"
    }
   ]
  },
  {
   "title": "Shoots in Error State",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(garden_shoot_operations_total{iaas=~\"$iaas\", state=\"Error\"})"
    }
   ]
  },
  {
   "title": "Shoots in Failed State",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(garden_shoot_operations_total{iaas=~\"$iaas\", state=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Count of Shoots in Last Operation Phase",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Shoot Count" }
   ],
   "targets": [
    {
     "expr": "sum(garden_shoot_operations_total{iaas=~\"$iaas\"}) by (operation, state)",
     "legendFormat": "{{operation}}/{{state}}"
    }
   ]
  },
  {
   "title": "Count of Shoots in Last Operation Phase grouped by Kubernetes Versions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Shoot Count" }
   ],
   "targets": [
    {
     "expr": "sum(garden_shoot_operations_total{iaas=~\"$iaas\"}) by (operation, state, version)",
     "legendFormat": "v{{version}} – {{operation}}/{{state}}"
    }
   ]
  },
  {
   "title": "Count of Shoots in Last Operation Phase grouped by Regions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Shoot Count" }
   ],
   "targets": [
    {
     "expr": "sum(garden_shoot_operations_total{iaas=~\"$iaas\"}) by (operation, state, region)",
     "legendFormat": "{{region}} – {{operation}}/{{state}}"
    }
   ]
  },
  {
   "title": "Count of Shoots in Last Operation Phase grouped by Seeds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Shoot Count" }
   ],
   "targets": [
    {
     "expr": "sum(garden_shoot_operations_total{iaas=~\"$iaas\"}) by (operation, state, seed)",
     "legendFormat": "{{seed}} – {{operation}}/{{state}}"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Shoot with Issues ($iaas)",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(garden_shoot_operation_states) by (name, project, operation) + ignoring(iaas, region, seed, version, operation) group_left sum(garden_shoot_info{iaas=~\"$iaas\"}) by (name, project, operation) > 3"
    }
   ]
  },
  {
   "title": "Shoot with False Conditions ($iaas)",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(garden_shoot_condition) by (name, project, condition) + ignoring(iaas, region, seed, version, condition, operation, mail_to) group_left sum(garden_shoot_info{iaas=~\"$iaas\"}) by (name, project, condition) == 0"
    }
   ]
  }
 ]
}