{
 "title": "Usage Overview",
 "description": "Dashboard with information to the usage of a Gardner landscape.",
 "tags": [
  "Gardener",
  "Usage"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "iaas",
    "label": "Infrastructure",
    "query": "label_values(garden_shoot_operations_total, iaas)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overall Shoots",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(garden_shoot_operations_total{iaas=~\"$iaas\"})"
    }
   ]
  },
  {
   "title": "Count Project",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "garden_projects_total" }
   ]
  },
  {
   "title": "Count Users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "garden_users_total" }
   ]
  },
  {
   "title": "Minimum Node Count ($iaas)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum(sum(garden_shoot_info{iaas=~\"$iaas\"}) by (iaas, region, name, project) + ignoring(iaas, region) group_left sum(garden_shoot_node_min_total) by (name, project)) by (iaas, region))"
    }
   ]
  },
  {
   "title": "Maximum Node Cound ($iaas)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum(sum(garden_shoot_info{iaas=~\"$iaas\"}) by (iaas, region, name, project) + ignoring(iaas, region) group_left sum(garden_shoot_node_max_total) by (name, project)) by (iaas, region))"
    }
   ]
  },
  {
   "title": "Shoot Count by Infrastructure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "Shoot Count" }
   ],
   "targets": [
    {
     "expr": "sum(garden_shoot_operations_total{iaas=~\"$iaas\"}) by (iaas)",
     "legendFormat": "{{iaas}}"
    }
   ]
  },
  {
   "title": "Shoot Count by Kubernetes Versions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "Shoot Count" }
   ],
   "targets": [
    {
     "expr": "sum(garden_shoot_operations_total{iaas=~\"$iaas\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Shoots per Region",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Shoot Count" }
   ],
   "targets": [
    {
     "expr": "sum(garden_shoot_operations_total{iaas=~\"$iaas\"}) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Control planes per Seed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Shoot Count" }
   ],
   "targets": [
    {
     "expr": "sum(garden_shoot_operations_total{iaas=~\"$iaas\"}) by(seed)",
     "legendFormat": "{{seed}}"
    }
   ]
  },
  {
   "title": "Shoot Count in Detail",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Shoot Count" }
   ],
   "targets": [
    {
     "expr": "sum(garden_shoot_operations_total{iaas=~\"$iaas\"}) by(iaas,version,region,seed) ",
     "legendFormat": "IAAS: {{iaas}}, K8S VERSION: v{{version}}, REGION: {{region}}, SEED: {{seed}}"
    }
   ]
  }
 ]
}