global:
  virtualGarden:
    enabled: false
    user:
      name: ""
  server:
    bindAddress: 0.0.0.0
    port: 2718
  image:
    repository: europe-docker.pkg.dev/gardener-project/public/gardener/metrics-exporter
    tag: latest
    pullPolicy: IfNotPresent
  # kubeconfig: a3ViZWNvbmZpZwo=

  resources:
    requests:
      cpu: 100m
      memory: 128Mi

  securityContext:
    readOnlyRootFilesystem: true

  serviceAccountTokenVolumeProjection:
    enabled: false
    expirationSeconds: 43200
    audience: ""
